<?php

namespace Database\Seeders;

use App\Models\Level;
use App\Models\Unit;
use App\Models\Lesson;
use App\Models\VocabularyCategory;
use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class ExtendedCurriculumSeeder extends Seeder
{
    /**
     * Pelajaran 3-25 (Minna no Nihongo I, complete).
     * Vocabulary word/reading/meaning pairs are dictionary-style
     * facts taken from the book's kosakata lists. No example
     * sentences, dialogues, or grammar prose are copied here.
     * Romaji added for app use.
     */
    public function run(): void
    {
        $n5 = Level::where('code', 'N5')->firstOrFail();
        $previousLesson = Lesson::whereHas('unit', fn ($q) => $q->where('order', 2))
            ->where('order', 2)->first();
        $previousUnit = Unit::where('order', 2)->first();

        foreach ($this->curriculum() as $order => $lesson) {
            $unit = Unit::firstOrCreate(
                ['level_id' => $n5->id, 'order' => $order],
                [
                    'title_id' => "Pelajaran {$order}: {$lesson['title_id']}",
                    'title_en' => "Lesson {$order}: {$lesson['title_en']}",
                    'icon' => 'mdi-book-open-page-variant',
                    'prerequisite_unit_id' => $previousUnit?->id,
                    'is_active' => true,
                ]
            );

            $category = VocabularyCategory::firstOrCreate(
                ['slug' => "pelajaran-{$order}"],
                [
                    'name_id' => "Kosakata Pelajaran {$order}",
                    'name_en' => "Lesson {$order} Vocabulary",
                ]
            );

            $newLesson = Lesson::firstOrCreate(
                ['unit_id' => $unit->id, 'order' => 1],
                [
                    'title_id' => $lesson['title_id'],
                    'title_en' => $lesson['title_en'],
                    'category' => 'vocabulary',
                    'xp_reward' => 10,
                    'required_accuracy' => 70,
                    'prerequisite_lesson_id' => $previousLesson?->id,
                    'is_active' => true,
                ]
            );

            foreach ($lesson['words'] as $w) {
                Vocabulary::firstOrCreate(
                    ['japanese' => $w[0], 'hiragana' => $w[1]],
                    [
                        'romaji' => $w[2],
                        'meaning_id' => $w[3],
                        'meaning_en' => $w[4],
                        'category_id' => $category->id,
                        'jlpt_level' => 'N5',
                        'difficulty' => 1,
                        'is_active' => true,
                    ]
                );
            }

            $previousUnit = $unit;
            $previousLesson = $newLesson;
        }
    }

    private function curriculum(): array
    {
        return [
            3 => [
                'title_id' => 'Tempat & Ruangan',
                'title_en' => 'Places & Rooms',
                'words' => [
                    ['ここ', 'ここ', 'koko', 'sini', 'here'],
                    ['そこ', 'そこ', 'soko', 'situ', 'there (near listener)'],
                    ['あそこ', 'あそこ', 'asoko', 'sana', 'over there'],
                    ['どこ', 'どこ', 'doko', '(di) mana', 'where'],
                    ['こちら', 'こちら', 'kochira', 'sini (sopan)', 'here (polite)'],
                    ['そちら', 'そちら', 'sochira', 'situ (sopan)', 'there (polite)'],
                    ['あちら', 'あちら', 'achira', 'sana (sopan)', 'over there (polite)'],
                    ['どちら', 'どちら', 'dochira', 'mana (sopan)', 'where (polite)'],
                    ['教室', 'きょうしつ', 'kyoushitsu', 'ruang kelas', 'classroom'],
                    ['食堂', 'しょくどう', 'shokudou', 'ruang makan, kantin', 'cafeteria'],
                    ['事務所', 'じむしょ', 'jimusho', 'kantor', 'office'],
                    ['会議室', 'かいぎしつ', 'kaigishitsu', 'ruang rapat', 'meeting room'],
                    ['受付', 'うけつけ', 'uketsuke', 'meja informasi', 'reception desk'],
                    ['ロビー', 'ロビー', 'robii', 'ruang tunggu, lobi', 'lobby'],
                    ['部屋', 'へや', 'heya', 'kamar', 'room'],
                    ['トイレ', 'トイレ', 'toire', 'kamar kecil, toilet', 'toilet'],
                    ['階段', 'かいだん', 'kaidan', 'tangga', 'stairs'],
                    ['エレベーター', 'エレベーター', 'erebeetaa', 'lift', 'elevator'],
                    ['エスカレーター', 'エスカレーター', 'esukareetaa', 'tangga berjalan, eskalator', 'escalator'],
                    ['自動販売機', 'じどうはんばいき', 'jidouhanbaiki', 'mesin jual otomatis', 'vending machine'],
                    ['電話', 'でんわ', 'denwa', 'telepon', 'telephone'],
                    ['国', 'くに', 'kuni', 'negara, negeri', 'country'],
                    ['会社', 'かいしゃ', 'kaisha', 'perusahaan', 'company'],
                    ['うち', 'うち', 'uchi', 'rumah', 'home'],
                ],
            ],
            4 => [
                'title_id' => 'Waktu & Hari',
                'title_en' => 'Time & Days',
                'words' => [
                    ['起きます', 'おきます', 'okimasu', 'bangun', 'wake up'],
                    ['寝ます', 'ねます', 'nemasu', 'tidur', 'sleep'],
                    ['働きます', 'はたらきます', 'hatarakimasu', 'bekerja', 'work'],
                    ['休みます', 'やすみます', 'yasumimasu', 'beristirahat, libur', 'rest / take a day off'],
                    ['勉強します', 'べんきょうします', 'benkyoushimasu', 'belajar', 'study'],
                    ['終わります', 'おわります', 'owarimasu', 'selesai', 'finish'],
                    ['デパート', 'デパート', 'depaato', 'toserba', 'department store'],
                    ['銀行', 'ぎんこう', 'ginkou', 'bank', 'bank'],
                    ['郵便局', 'ゆうびんきょく', 'yuubinkyoku', 'kantor pos', 'post office'],
                    ['図書館', 'としょかん', 'toshokan', 'perpustakaan', 'library'],
                    ['美術館', 'びじゅつかん', 'bijutsukan', 'gedung kesenian', 'art museum'],
                    ['今', 'いま', 'ima', 'sekarang', 'now'],
                    ['時', 'じ', '-ji', 'jam -, pukul -', 'o\'clock'],
                    ['分', 'ふん', '-fun', '- menit', '- minutes'],
                    ['半', 'はん', 'han', 'setengah', 'half past'],
                    ['何時', 'なんじ', 'nanji', 'jam berapa', 'what time'],
                    ['何分', 'なんぷん', 'nanpun', 'berapa menit', 'how many minutes'],
                    ['午前', 'ごぜん', 'gozen', 'a.m.', 'a.m.'],
                    ['午後', 'ごご', 'gogo', 'p.m.', 'p.m.'],
                    ['朝', 'あさ', 'asa', 'pagi', 'morning'],
                    ['昼', 'ひる', 'hiru', 'siang', 'daytime'],
                    ['晩', 'ばん', 'ban', 'malam', 'evening'],
                    ['おととい', 'おととい', 'ototoi', 'kemarin lusa', 'two days ago'],
                    ['きのう', 'きのう', 'kinou', 'kemarin', 'yesterday'],
                    ['きょう', 'きょう', 'kyou', 'hari ini', 'today'],
                    ['あした', 'あした', 'ashita', 'besok', 'tomorrow'],
                    ['あさって', 'あさって', 'asatte', 'lusa', 'day after tomorrow'],
                    ['けさ', 'けさ', 'kesa', 'pagi ini, tadi pagi', 'this morning'],
                    ['今晩', 'こんばん', 'konban', 'malam ini', 'tonight'],
                    ['休み', 'やすみ', 'yasumi', 'istirahat, cuti, libur', 'holiday / break'],
                    ['昼休み', 'ひるやすみ', 'hiruyasumi', 'istirahat siang', 'lunch break'],
                    ['試験', 'しけん', 'shiken', 'ujian', 'exam'],
                    ['会議', 'かいぎ', 'kaigi', 'rapat', 'meeting'],
                    ['映画', 'えいが', 'eiga', 'film', 'movie'],
                    ['毎朝', 'まいあさ', 'maiasa', 'setiap pagi', 'every morning'],
                    ['毎晩', 'まいばん', 'maiban', 'setiap malam', 'every night'],
                    ['毎日', 'まいにち', 'mainichi', 'setiap hari', 'every day'],
                    ['月曜日', 'げつようび', 'getsuyoubi', 'hari Senin', 'Monday'],
                    ['火曜日', 'かようび', 'kayoubi', 'hari Selasa', 'Tuesday'],
                    ['水曜日', 'すいようび', 'suiyoubi', 'hari Rabu', 'Wednesday'],
                    ['木曜日', 'もくようび', 'mokuyoubi', 'hari Kamis', 'Thursday'],
                    ['金曜日', 'きんようび', 'kinyoubi', 'hari Jumat', 'Friday'],
                    ['土曜日', 'どようび', 'doyoubi', 'hari Sabtu', 'Saturday'],
                    ['日曜日', 'にちようび', 'nichiyoubi', 'hari Minggu', 'Sunday'],
                    ['何曜日', 'なんようび', 'nanyoubi', 'hari apa', 'what day'],
                ],
            ],
            5 => [
                'title_id' => 'Transportasi & Keluarga',
                'title_en' => 'Transport & Family',
                'words' => [
                    ['行きます', 'いきます', 'ikimasu', 'pergi', 'go'],
                    ['来ます', 'きます', 'kimasu', 'datang', 'come'],
                    ['帰ります', 'かえります', 'kaerimasu', 'pulang', 'return'],
                    ['学校', 'がっこう', 'gakkou', 'sekolah', 'school'],
                    ['スーパー', 'スーパー', 'suupaa', 'pasar swalayan', 'supermarket'],
                    ['駅', 'えき', 'eki', 'stasiun', 'station'],
                    ['飛行機', 'ひこうき', 'hikouki', 'pesawat terbang', 'airplane'],
                    ['船', 'ふね', 'fune', 'kapal laut', 'ship'],
                    ['電車', 'でんしゃ', 'densha', 'kereta rel listrik', 'train'],
                    ['地下鉄', 'ちかてつ', 'chikatetsu', 'kereta bawah tanah', 'subway'],
                    ['新幹線', 'しんかんせん', 'shinkansen', 'Shinkansen', 'bullet train'],
                    ['バス', 'バス', 'basu', 'bus', 'bus'],
                    ['タクシー', 'タクシー', 'takushii', 'taksi', 'taxi'],
                    ['自転車', 'じてんしゃ', 'jitensha', 'sepeda', 'bicycle'],
                    ['歩いて', 'あるいて', 'aruite', 'dengan berjalan kaki', 'on foot'],
                    ['人', 'ひと', 'hito', 'orang', 'person'],
                    ['友達', 'ともだち', 'tomodachi', 'teman', 'friend'],
                    ['彼', 'かれ', 'kare', 'dia (laki-laki)', 'he'],
                    ['彼女', 'かのじょ', 'kanojo', 'dia (perempuan)', 'she'],
                    ['家族', 'かぞく', 'kazoku', 'keluarga', 'family'],
                    ['一人で', 'ひとりで', 'hitoride', 'sendirian', 'alone'],
                    ['先週', 'せんしゅう', 'senshuu', 'minggu lalu', 'last week'],
                    ['今週', 'こんしゅう', 'konshuu', 'minggu ini', 'this week'],
                    ['来週', 'らいしゅう', 'raishuu', 'minggu depan', 'next week'],
                    ['先月', 'せんげつ', 'sengetsu', 'bulan lalu', 'last month'],
                    ['今月', 'こんげつ', 'kongetsu', 'bulan ini', 'this month'],
                    ['来月', 'らいげつ', 'raigetsu', 'bulan depan', 'next month'],
                    ['去年', 'きょねん', 'kyonen', 'tahun lalu', 'last year'],
                    ['ことし', 'ことし', 'kotoshi', 'tahun ini', 'this year'],
                    ['来年', 'らいねん', 'rainen', 'tahun depan', 'next year'],
                    ['年', 'ねん', '-nen', 'tahun -', '- year(s)'],
                    ['何年', 'なんねん', 'nannen', 'tahun berapa', 'which year'],
                    ['月', 'がつ', '-gatsu', 'bulan -', 'month of -'],
                    ['何月', 'なんがつ', 'nangatsu', 'bulan apa', 'which month'],
                ],
            ],
            6 => [
                'title_id' => 'Aktivitas & Makanan',
                'title_en' => 'Activities & Food',
                'words' => [
                    ['食べます', 'たべます', 'tabemasu', 'makan', 'eat'],
                    ['飲みます', 'のみます', 'nomimasu', 'minum', 'drink'],
                    ['吸います', 'すいます', 'suimasu', 'mengisap rokok, merokok', 'smoke'],
                    ['見ます', 'みます', 'mimasu', 'melihat, menonton', 'watch / see'],
                    ['聞きます', 'ききます', 'kikimasu', 'mendengar', 'listen / hear'],
                    ['読みます', 'よみます', 'yomimasu', 'membaca', 'read'],
                    ['書きます', 'かきます', 'kakimasu', 'menulis, menggambar', 'write / draw'],
                    ['買います', 'かいます', 'kaimasu', 'membeli', 'buy'],
                    ['撮ります', 'とります', 'torimasu', 'mengambil foto', 'take a photo'],
                    ['します', 'します', 'shimasu', 'mengerjakan, melakukan', 'do'],
                    ['会います', 'あいます', 'aimasu', 'bertemu', 'meet'],
                    ['ごはん', 'ごはん', 'gohan', 'nasi', 'rice / meal'],
                    ['朝ごはん', 'あさごはん', 'asagohan', 'sarapan', 'breakfast'],
                    ['昼ごはん', 'ひるごはん', 'hirugohan', 'makan siang', 'lunch'],
                    ['晩ごはん', 'ばんごはん', 'bangohan', 'makan malam', 'dinner'],
                    ['パン', 'パン', 'pan', 'roti', 'bread'],
                    ['卵', 'たまご', 'tamago', 'telur', 'egg'],
                    ['肉', 'にく', 'niku', 'daging', 'meat'],
                    ['魚', 'さかな', 'sakana', 'ikan', 'fish'],
                    ['野菜', 'やさい', 'yasai', 'sayur', 'vegetable'],
                    ['果物', 'くだもの', 'kudamono', 'buah-buahan', 'fruit'],
                    ['水', 'みず', 'mizu', 'air', 'water'],
                    ['お茶', 'おちゃ', 'ocha', 'teh', 'tea'],
                    ['紅茶', 'こうちゃ', 'koucha', 'teh', 'black tea'],
                    ['牛乳', 'ぎゅうにゅう', 'gyuunyuu', 'susu', 'milk'],
                    ['ジュース', 'ジュース', 'juusu', 'jus', 'juice'],
                    ['ビール', 'ビール', 'biiru', 'bir', 'beer'],
                    ['お酒', 'おさけ', 'osake', 'minuman keras', 'alcohol'],
                    ['たばこ', 'たばこ', 'tabako', 'rokok', 'cigarette'],
                ],
            ],
            7 => [
                'title_id' => 'Alat Tulis & Barang',
                'title_en' => 'Stationery & Items',
                'words' => [
                    ['切ります', 'きります', 'kirimasu', 'memotong, menggunting', 'cut'],
                    ['送ります', 'おくります', 'okurimasu', 'mengirim', 'send'],
                    ['あげます', 'あげます', 'agemasu', 'memberikan', 'give'],
                    ['もらいます', 'もらいます', 'moraimasu', 'mendapatkan, menerima', 'receive'],
                    ['貸します', 'かします', 'kashimasu', 'meminjamkan, menyewakan', 'lend'],
                    ['借ります', 'かります', 'karimasu', 'meminjam, menyewa', 'borrow'],
                    ['教えます', 'おしえます', 'oshiemasu', 'mengajar', 'teach'],
                    ['習います', 'ならいます', 'naraimasu', 'belajar', 'learn'],
                    ['かけます', 'かけます', 'kakemasu', 'menelepon', 'make a call'],
                    ['手', 'て', 'te', 'tangan', 'hand'],
                    ['はし', 'はし', 'hashi', 'sumpit', 'chopsticks'],
                    ['スプーン', 'スプーン', 'supuun', 'sendok', 'spoon'],
                    ['ナイフ', 'ナイフ', 'naifu', 'pisau', 'knife'],
                    ['フォーク', 'フォーク', 'fooku', 'garpu', 'fork'],
                    ['はさみ', 'はさみ', 'hasami', 'gunting', 'scissors'],
                    ['パソコン', 'パソコン', 'pasokon', 'komputer, PC', 'PC'],
                    ['ケータイ', 'ケータイ', 'keetai', 'HP', 'mobile phone'],
                    ['メール', 'メール', 'meeru', 'e-mail', 'email'],
                    ['年賀状', 'ねんがじょう', 'nengajou', 'kartu tahun baru', 'New Year card'],
                    ['パンチ', 'パンチ', 'panchi', 'pelubang kertas', 'hole punch'],
                    ['ホッチキス', 'ホッチキス', 'hocchikisu', 'staplr', 'stapler'],
                    ['セロテープ', 'セロテープ', 'seroteepu', 'selotip', 'tape'],
                    ['消しゴム', 'けしゴム', 'keshigomu', 'penghapus karet', 'eraser'],
                    ['紙', 'かみ', 'kami', 'kertas', 'paper'],
                    ['花', 'はな', 'hana', 'bunga', 'flower'],
                    ['シャツ', 'シャツ', 'shatsu', 'kemeja', 'shirt'],
                    ['プレゼント', 'プレゼント', 'purezento', 'kado, hadiah', 'present'],
                    ['荷物', 'にもつ', 'nimotsu', 'barang', 'luggage'],
                    ['お金', 'おかね', 'okane', 'uang', 'money'],
                    ['切符', 'きっぷ', 'kippu', 'karcis', 'ticket'],
                    ['クリスマス', 'クリスマス', 'kurisumasu', 'Natal', 'Christmas'],
                ],
            ],
            8 => [
                'title_id' => 'Sifat & Warna',
                'title_en' => 'Adjectives & Colors',
                'words' => [
                    ['ハンサム', 'ハンサム', 'hansamu', 'tampan, gagah', 'handsome'],
                    ['きれい', 'きれい', 'kirei', 'cantik, bersih', 'pretty / clean'],
                    ['静か', 'しずか', 'shizuka', 'sunyi, tenang', 'quiet'],
                    ['にぎやか', 'にぎやか', 'nigiyaka', 'ramai', 'lively'],
                    ['有名', 'ゆうめい', 'yuumei', 'terkenal', 'famous'],
                    ['親切', 'しんせつ', 'shinsetsu', 'baik hati', 'kind'],
                    ['元気', 'げんき', 'genki', 'sehat walafiat', 'healthy / energetic'],
                    ['暇', 'ひま', 'hima', 'senggang', 'free time'],
                    ['便利', 'べんり', 'benri', 'praktis', 'convenient'],
                    ['すてき', 'すてき', 'suteki', 'bagus', 'lovely'],
                    ['大きい', 'おおきい', 'ookii', 'besar', 'big'],
                    ['小さい', 'ちいさい', 'chiisai', 'kecil', 'small'],
                    ['新しい', 'あたらしい', 'atarashii', 'baru', 'new'],
                    ['古い', 'ふるい', 'furui', 'lama, tua', 'old'],
                    ['いい', 'いい', 'ii', 'baik, bagus', 'good'],
                    ['悪い', 'わるい', 'warui', 'buruk, jelek', 'bad'],
                    ['暑い', 'あつい', 'atsui', 'panas', 'hot (weather)'],
                    ['寒い', 'さむい', 'samui', 'dingin (suhu udara)', 'cold (weather)'],
                    ['冷たい', 'つめたい', 'tsumetai', 'dingin (benda)', 'cold (object)'],
                    ['難しい', 'むずかしい', 'muzukashii', 'sulit, susah', 'difficult'],
                    ['易しい', 'やさしい', 'yasashii', 'mudah, gampang', 'easy'],
                    ['高い', 'たかい', 'takai', 'mahal, tinggi', 'expensive / tall'],
                    ['安い', 'やすい', 'yasui', 'murah', 'cheap'],
                    ['低い', 'ひくい', 'hikui', 'rendah', 'low'],
                    ['面白い', 'おもしろい', 'omoshiroi', 'menarik', 'interesting'],
                    ['おいしい', 'おいしい', 'oishii', 'enak', 'delicious'],
                    ['忙しい', 'いそがしい', 'isogashii', 'sibuk', 'busy'],
                    ['楽しい', 'たのしい', 'tanoshii', 'senang', 'fun'],
                    ['白い', 'しろい', 'shiroi', 'putih', 'white'],
                    ['黒い', 'くろい', 'kuroi', 'hitam', 'black'],
                    ['赤い', 'あかい', 'akai', 'merah', 'red'],
                    ['青い', 'あおい', 'aoi', 'biru', 'blue'],
                    ['桜', 'さくら', 'sakura', 'sakura', 'cherry blossom'],
                    ['山', 'やま', 'yama', 'gunung', 'mountain'],
                    ['町', 'まち', 'machi', 'kota', 'town'],
                    ['食べ物', 'たべもの', 'tabemono', 'makanan', 'food'],
                ],
            ],
            9 => [
                'title_id' => 'Hobi & Kesenangan',
                'title_en' => 'Hobbies & Interests',
                'words' => [
                    ['わかります', 'わかります', 'wakarimasu', 'mengerti', 'understand'],
                    ['あります', 'あります', 'arimasu', 'ada, mempunyai', 'have / exist'],
                    ['好き', 'すき', 'suki', 'suka, gemar', 'like'],
                    ['嫌い', 'きらい', 'kirai', 'tidak suka', 'dislike'],
                    ['上手', 'じょうず', 'jouzu', 'pandai, pintar', 'skillful'],
                    ['下手', 'へた', 'heta', 'tidak pandai', 'unskillful'],
                    ['飲み物', 'のみもの', 'nomimono', 'minuman', 'beverage'],
                    ['料理', 'りょうり', 'ryouri', 'masakan', 'cooking'],
                    ['スポーツ', 'スポーツ', 'supootsu', 'olahraga', 'sports'],
                    ['野球', 'やきゅう', 'yakyuu', 'baseball', 'baseball'],
                    ['ダンス', 'ダンス', 'dansu', 'dansa', 'dance'],
                    ['旅行', 'りょこう', 'ryokou', 'tamasya', 'travel'],
                    ['音楽', 'おんがく', 'ongaku', 'musik', 'music'],
                    ['歌', 'うた', 'uta', 'lagu', 'song'],
                    ['クラシック', 'クラシック', 'kurashikku', 'musik klasik', 'classical music'],
                    ['ジャズ', 'ジャズ', 'jazu', 'jaz', 'jazz'],
                    ['コンサート', 'コンサート', 'konsaato', 'konser', 'concert'],
                    ['カラオケ', 'カラオケ', 'karaoke', 'karaoke', 'karaoke'],
                    ['歌舞伎', 'かぶき', 'kabuki', 'Kabuki', 'Kabuki theater'],
                    ['絵', 'え', 'e', 'gambar', 'picture'],
                    ['字', 'じ', 'ji', 'huruf', 'character'],
                    ['漢字', 'かんじ', 'kanji', 'Kanji', 'kanji'],
                    ['ひらがな', 'ひらがな', 'hiragana', 'Hiragana', 'hiragana'],
                    ['かたかな', 'かたかな', 'katakana', 'Katakana', 'katakana'],
                    ['ローマ字', 'ローマじ', 'roomaji', 'huruf latin', 'romaji'],
                    ['細かいお金', 'こまかいおかね', 'komakai okane', 'uang kecil, receh', 'small change'],
                    ['チケット', 'チケット', 'chiketto', 'tiket', 'ticket'],
                    ['時間', 'じかん', 'jikan', 'jam, waktu', 'time'],
                    ['用事', 'ようじ', 'youji', 'urusan', 'errand'],
                    ['約束', 'やくそく', 'yakusoku', 'janji', 'promise'],
                ],
            ],
            10 => [
                'title_id' => 'Di Dalam Rumah',
                'title_en' => 'Inside the House',
                'words' => [
                    ['あります', 'あります', 'arimasu', 'ada (benda mati)', 'there is (inanimate)'],
                    ['います', 'います', 'imasu', 'ada (makhluk hidup)', 'there is (animate)'],
                    ['いろいろ', 'いろいろ', 'iroiro', 'berbagai', 'various'],
                    ['男の人', 'おとこのひと', 'otoko no hito', 'orang laki-laki', 'man'],
                    ['女の人', 'おんなのひと', 'onna no hito', 'orang perempuan', 'woman'],
                    ['男の子', 'おとこのこ', 'otoko no ko', 'anak laki-laki', 'boy'],
                    ['女の子', 'おんなのこ', 'onna no ko', 'anak perempuan', 'girl'],
                    ['犬', 'いぬ', 'inu', 'anjing', 'dog'],
                    ['猫', 'ねこ', 'neko', 'kucing', 'cat'],
                    ['パンダ', 'パンダ', 'panda', 'panda', 'panda'],
                    ['象', 'ぞう', 'zou', 'gajah', 'elephant'],
                    ['木', 'き', 'ki', 'pohon', 'tree'],
                    ['物', 'もの', 'mono', 'barang', 'thing'],
                    ['電池', 'でんち', 'denchi', 'baterai', 'battery'],
                    ['箱', 'はこ', 'hako', 'kotak', 'box'],
                    ['スイッチ', 'スイッチ', 'suicchi', 'tombol, sakelar', 'switch'],
                    ['冷蔵庫', 'れいぞうこ', 'reizouko', 'kulkas, lemari es', 'refrigerator'],
                    ['テーブル', 'テーブル', 'teeburu', 'meja makan', 'table'],
                    ['ベッド', 'ベッド', 'beddo', 'tempat tidur', 'bed'],
                    ['棚', 'たな', 'tana', 'lemari', 'shelf'],
                    ['ドア', 'ドア', 'doa', 'pintu', 'door'],
                    ['窓', 'まど', 'mado', 'jendela', 'window'],
                    ['ポスト', 'ポスト', 'posuto', 'kotak surat', 'mailbox'],
                    ['ビル', 'ビル', 'biru', 'gedung', 'building'],
                    ['ATM', 'ATM', 'eetiiemu', 'ATM', 'ATM'],
                    ['コンビニ', 'コンビニ', 'konbini', 'toko 24 jam', 'convenience store'],
                    ['公園', 'こうえん', 'kouen', 'taman', 'park'],
                    ['喫茶店', 'きっさてん', 'kissaten', 'coffee shop', 'cafe'],
                    ['屋', 'や', '-ya', 'toko ~', '~ shop'],
                    ['乗り場', 'のりば', 'noriba', 'tempat naik', 'boarding area'],
                    ['県', 'けん', 'ken', 'prefektur', 'prefecture'],
                ],
            ],
            11 => [
                'title_id' => 'Bilangan & Keluarga',
                'title_en' => 'Numbers & Family',
                'words' => [
                    ['かかります', 'かかります', 'kakarimasu', 'memakan waktu/uang', 'take (time/money)'],
                    ['一つ', 'ひとつ', 'hitotsu', 'satu', 'one (items)'],
                    ['二つ', 'ふたつ', 'futatsu', 'dua', 'two (items)'],
                    ['三つ', 'みっつ', 'mittsu', 'tiga', 'three (items)'],
                    ['四つ', 'よっつ', 'yottsu', 'empat', 'four (items)'],
                    ['五つ', 'いつつ', 'itsutsu', 'lima', 'five (items)'],
                    ['六つ', 'むっつ', 'muttsu', 'enam', 'six (items)'],
                    ['七つ', 'ななつ', 'nanatsu', 'tujuh', 'seven (items)'],
                    ['八つ', 'やっつ', 'yattsu', 'delapan', 'eight (items)'],
                    ['九つ', 'ここのつ', 'kokonotsu', 'sembilan', 'nine (items)'],
                    ['十', 'とお', 'too', 'sepuluh', 'ten (items)'],
                    ['いくつ', 'いくつ', 'ikutsu', 'berapa', 'how many'],
                    ['一人', 'ひとり', 'hitori', 'seorang', 'one person'],
                    ['二人', 'ふたり', 'futari', 'dua orang', 'two people'],
                    ['人', 'にん', '-nin', '~ orang', '~ people'],
                    ['台', 'だい', '-dai', 'buah (mesin, mobil)', '(counter: machines)'],
                    ['枚', 'まい', '-mai', 'lembar, helai', '(counter: flat objects)'],
                    ['回', 'かい', '-kai', '~ kali', '~ times'],
                    ['りんご', 'りんご', 'ringo', 'apel', 'apple'],
                    ['みかん', 'みかん', 'mikan', 'jeruk', 'mandarin orange'],
                    ['サンドイッチ', 'サンドイッチ', 'sandoicchi', 'sandwich', 'sandwich'],
                    ['カレーライス', 'カレーライス', 'karee raisu', 'nasi kare', 'curry rice'],
                    ['アイスクリーム', 'アイスクリーム', 'aisukuriimu', 'es krim', 'ice cream'],
                    ['切手', 'きって', 'kitte', 'perangko', 'stamp'],
                    ['はがき', 'はがき', 'hagaki', 'kartu pos', 'postcard'],
                    ['封筒', 'ふうとう', 'fuutou', 'amplop', 'envelope'],
                    ['両親', 'りょうしん', 'ryoushin', 'orang tua', 'parents'],
                    ['兄弟', 'きょうだい', 'kyoudai', 'saudara', 'siblings'],
                    ['兄', 'あに', 'ani', 'kakak laki-laki (sendiri)', 'older brother (own)'],
                    ['お兄さん', 'おにいさん', 'oniisan', 'kakak laki-laki (orang lain)', 'older brother (others\')'],
                    ['姉', 'あね', 'ane', 'kakak perempuan (sendiri)', 'older sister (own)'],
                    ['お姉さん', 'おねえさん', 'oneesan', 'kakak perempuan (orang lain)', 'older sister (others\')'],
                    ['弟', 'おとうと', 'otouto', 'adik laki-laki (sendiri)', 'younger brother (own)'],
                    ['弟さん', 'おとうとさん', 'otoutosan', 'adik laki-laki (orang lain)', 'younger brother (others\')'],
                    ['妹', 'いもうと', 'imouto', 'adik perempuan (sendiri)', 'younger sister (own)'],
                    ['妹さん', 'いもうとさん', 'imoutosan', 'adik perempuan (orang lain)', 'younger sister (others\')'],
                    ['外国', 'がいこく', 'gaikoku', 'luar negeri', 'foreign country'],
                    ['留学生', 'りゅうがくせい', 'ryuugakusei', 'pelajar asing', 'international student'],
                    ['クラス', 'クラス', 'kurasu', 'kelas', 'class'],
                    ['時間', 'じかん', '-jikan', '~ jam', '~ hours'],
                    ['週間', 'しゅうかん', '-shuukan', '~ minggu', '~ weeks'],
                    ['か月', 'かげつ', '-kagetsu', '~ bulan', '~ months'],
                    ['ぐらい', 'ぐらい', 'gurai', 'kira-kira', 'approximately'],
                    ['どのくらい', 'どのくらい', 'dono kurai', 'berapa lama', 'how long'],
                    ['全部で', 'ぜんぶで', 'zenbude', 'semuanya', 'in total'],
                    ['みんな', 'みんな', 'minna', 'semua', 'everyone'],
                    ['だけ', 'だけ', 'dake', 'hanya', 'only'],
                ],
            ],
            12 => [
                'title_id' => 'Musim & Cuaca',
                'title_en' => 'Seasons & Weather',
                'words' => [
                    ['簡単', 'かんたん', 'kantan', 'mudah, gampang', 'simple'],
                    ['近い', 'ちかい', 'chikai', 'dekat', 'near'],
                    ['遠い', 'とおい', 'tooi', 'jauh', 'far'],
                    ['速い', 'はやい', 'hayai', 'cepat', 'fast'],
                    ['遅い', 'おそい', 'osoi', 'lambat', 'slow'],
                    ['多い', 'おおい', 'ooi', 'banyak', 'many'],
                    ['少ない', 'すくない', 'sukunai', 'sedikit', 'few'],
                    ['暖かい', 'あたたかい', 'atatakai', 'hangat', 'warm'],
                    ['涼しい', 'すずしい', 'suzushii', 'sejuk', 'cool'],
                    ['甘い', 'あまい', 'amai', 'manis', 'sweet'],
                    ['辛い', 'からい', 'karai', 'pedas', 'spicy'],
                    ['重い', 'おもい', 'omoi', 'berat', 'heavy'],
                    ['軽い', 'かるい', 'karui', 'ringan', 'light'],
                    ['季節', 'きせつ', 'kisetsu', 'musim', 'season'],
                    ['春', 'はる', 'haru', 'musim semi', 'spring'],
                    ['夏', 'なつ', 'natsu', 'musim panas', 'summer'],
                    ['秋', 'あき', 'aki', 'musim gugur', 'autumn'],
                    ['冬', 'ふゆ', 'fuyu', 'musim dingin', 'winter'],
                    ['天気', 'てんき', 'tenki', 'cuaca', 'weather'],
                    ['雨', 'あめ', 'ame', 'hujan', 'rain'],
                    ['雪', 'ゆき', 'yuki', 'salju', 'snow'],
                    ['曇り', 'くもり', 'kumori', 'mendung', 'cloudy'],
                    ['ホテル', 'ホテル', 'hoteru', 'hotel', 'hotel'],
                    ['空港', 'くうこう', 'kuukou', 'bandara', 'airport'],
                    ['海', 'うみ', 'umi', 'laut', 'sea'],
                    ['世界', 'せかい', 'sekai', 'dunia', 'world'],
                    ['パーティー', 'パーティー', 'paatii', 'pesta', 'party'],
                    ['祭り', 'まつり', 'matsuri', 'perayaan', 'festival'],
                ],
            ],
            13 => [
                'title_id' => 'Rekreasi & Kota',
                'title_en' => 'Recreation & City',
                'words' => [
                    ['遊びます', 'あそびます', 'asobimasu', 'bermain', 'play'],
                    ['泳ぎます', 'およぎます', 'oyogimasu', 'berenang', 'swim'],
                    ['迎えます', 'むかえます', 'mukaemasu', 'menjemput', 'pick up (someone)'],
                    ['疲れます', 'つかれます', 'tsukaremasu', 'lelah', 'get tired'],
                    ['結婚します', 'けっこんします', 'kekkonshimasu', 'menikah', 'get married'],
                    ['買い物します', 'かいものします', 'kaimonoshimasu', 'berbelanja', 'go shopping'],
                    ['食事します', 'しょくじします', 'shokujishimasu', 'makan', 'have a meal'],
                    ['散歩します', 'さんぽします', 'sanposhimasu', 'berjalan-jalan', 'take a walk'],
                    ['大変', 'たいへん', 'taihen', 'berat, susah', 'tough'],
                    ['欲しい', 'ほしい', 'hoshii', 'ingin, mau', 'want'],
                    ['広い', 'ひろい', 'hiroi', 'luas', 'spacious'],
                    ['狭い', 'せまい', 'semai', 'sempit', 'narrow'],
                    ['プール', 'プール', 'puuru', 'kolam renang', 'pool'],
                    ['川', 'かわ', 'kawa', 'sungai', 'river'],
                    ['美術', 'びじゅつ', 'bijutsu', 'seni', 'art'],
                    ['釣り', 'つり', 'tsuri', 'pancing', 'fishing'],
                    ['スキー', 'スキー', 'sukii', 'ski', 'skiing'],
                    ['週末', 'しゅうまつ', 'shuumatsu', 'akhir pekan', 'weekend'],
                    ['正月', 'しょうがつ', 'shougatsu', 'tahun baru', 'New Year'],
                    ['ごろ', 'ごろ', 'goro', 'sekitar, kira-kira', 'around (time)'],
                    ['何か', 'なにか', 'nanika', 'sesuatu', 'something'],
                    ['どこか', 'どこか', 'dokoka', 'suatu tempat', 'somewhere'],
                ],
            ],
            14 => [
                'title_id' => 'Aktivitas di Stasiun',
                'title_en' => 'Activities at the Station',
                'words' => [
                    ['つけます', 'つけます', 'tsukemasu', 'menyalakan', 'turn on'],
                    ['消します', 'けします', 'keshimasu', 'mematikan', 'turn off'],
                    ['開けます', 'あけます', 'akemasu', 'membuka', 'open'],
                    ['閉めます', 'しめます', 'shimemasu', 'menutup', 'close'],
                    ['急ぎます', 'いそぎます', 'isogimasu', 'buru-buru', 'hurry'],
                    ['待ちます', 'まちます', 'machimasu', 'menunggu', 'wait'],
                    ['持ちます', 'もちます', 'mochimasu', 'membawa', 'hold / carry'],
                    ['取ります', 'とります', 'torimasu', 'mengambil', 'take'],
                    ['手伝います', 'てつだいます', 'tetsudaimasu', 'membantu', 'help'],
                    ['呼びます', 'よびます', 'yobimasu', 'memanggil', 'call out to'],
                    ['話します', 'はなします', 'hanashimasu', 'berbicara', 'speak'],
                    ['使います', 'つかいます', 'tsukaimasu', 'memakai', 'use'],
                    ['止めます', 'とめます', 'tomemasu', 'menghentikan, memarkir', 'stop / park'],
                    ['見せます', 'みせます', 'misemasu', 'memperlihatkan', 'show'],
                    ['教えます', 'おしえます', 'oshiemasu', 'memberitahukan alamat', 'tell (an address)'],
                    ['座ります', 'すわります', 'suwarimasu', 'duduk', 'sit'],
                    ['立ちます', 'たちます', 'tachimasu', 'berdiri', 'stand'],
                    ['入ります', 'はいります', 'hairimasu', 'masuk', 'enter'],
                    ['出ます', 'でます', 'demasu', 'keluar', 'exit'],
                    ['降ります', 'ふります', 'furimasu', 'turun (hujan)', 'fall (rain)'],
                    ['コピーします', 'コピーします', 'kopii shimasu', 'memfotokopi', 'photocopy'],
                    ['電気', 'でんき', 'denki', 'listrik, lampu', 'electricity / light'],
                    ['エアコン', 'エアコン', 'eakon', 'AC', 'air conditioner'],
                    ['パスポート', 'パスポート', 'pasupooto', 'paspor', 'passport'],
                    ['名前', 'なまえ', 'namae', 'nama', 'name'],
                    ['住所', 'じゅうしょ', 'juusho', 'alamat', 'address'],
                    ['地図', 'ちず', 'chizu', 'peta', 'map'],
                    ['塩', 'しお', 'shio', 'garam', 'salt'],
                    ['砂糖', 'さとう', 'satou', 'gula', 'sugar'],
                ],
            ],
            15 => [
                'title_id' => 'Pekerjaan & Kegiatan',
                'title_en' => 'Work & Activities',
                'words' => [
                    ['置きます', 'おきます', 'okimasu', 'meletakkan, menaruh', 'put / place'],
                    ['作ります', 'つくります', 'tsukurimasu', 'membuat, membangun', 'make / build'],
                    ['売ります', 'うります', 'urimasu', 'menjual', 'sell'],
                    ['知ります', 'しります', 'shirimasu', 'mengetahui, mengenal', 'get to know'],
                    ['住みます', 'すみます', 'sumimasu', 'tinggal', 'live / reside'],
                    ['研究します', 'けんきゅうします', 'kenkyuushimasu', 'meneliti', 'research'],
                    ['資料', 'しりょう', 'shiryou', 'data, bahan', 'material / data'],
                    ['カタログ', 'カタログ', 'katarogu', 'katalog', 'catalog'],
                    ['時刻表', 'じこくひょう', 'jikokuhyou', 'jadwal', 'timetable'],
                    ['服', 'ふく', 'fuku', 'baju', 'clothes'],
                    ['製品', 'せいひん', 'seihin', 'produk', 'product'],
                    ['ソフト', 'ソフト', 'sofuto', 'perangkat lunak', 'software'],
                    ['電子辞書', 'でんしじしょ', 'denshijisho', 'kamus elektronik', 'electronic dictionary'],
                    ['経済', 'けいざい', 'keizai', 'ekonomi', 'economics'],
                    ['市役所', 'しやくしょ', 'shiyakusho', 'kantor wali kota', 'city hall'],
                    ['高校', 'こうこう', 'koukou', 'SMA', 'high school'],
                    ['歯医者', 'はいしゃ', 'haisha', 'dokter gigi', 'dentist'],
                    ['独身', 'どくしん', 'dokushin', 'bujangan, belum berkeluarga', 'single (unmarried)'],
                ],
            ],
            16 => [
                'title_id' => 'Cara Menggunakan & Anggota Tubuh',
                'title_en' => 'How-to & Body Parts',
                'words' => [
                    ['乗ります', 'のります', 'norimasu', 'naik (kereta)', 'board / ride'],
                    ['降ります', 'おります', 'orimasu', 'turun (kereta)', 'get off'],
                    ['乗り換えます', 'のりかえます', 'norikaemasu', 'ganti, pindah', 'transfer / change'],
                    ['浴びます', 'あびます', 'abimasu', 'mandi (shower)', 'take a shower'],
                    ['入れます', 'いれます', 'iremasu', 'memasukkan', 'put in'],
                    ['出します', 'だします', 'dashimasu', 'mengeluarkan, mengirim', 'take out / send'],
                    ['下ろします', 'おろします', 'oroshimasu', 'mengeluarkan uang', 'withdraw (money)'],
                    ['入ります', 'はいります', 'hairimasu', 'masuk universitas', 'enter (university)'],
                    ['出ます', 'でます', 'demasu', 'tamat universitas', 'graduate'],
                    ['押します', 'おします', 'oshimasu', 'menekan', 'push'],
                    ['始めます', 'はじめます', 'hajimemasu', 'mulai', 'begin'],
                    ['見学します', 'けんがくします', 'kengakushimasu', 'mengunjungi', 'observe / tour'],
                    ['電話します', 'でんわします', 'denwashimasu', 'menelepon', 'make a phone call'],
                    ['若い', 'わかい', 'wakai', 'muda', 'young'],
                    ['長い', 'ながい', 'nagai', 'panjang', 'long'],
                    ['短い', 'みじかい', 'mijikai', 'pendek', 'short'],
                    ['明るい', 'あかるい', 'akarui', 'terang', 'bright'],
                    ['暗い', 'くらい', 'kurai', 'gelap', 'dark'],
                    ['体', 'からだ', 'karada', 'badan', 'body'],
                    ['頭', 'あたま', 'atama', 'kepala', 'head'],
                    ['髪', 'かみ', 'kami', 'rambut', 'hair'],
                    ['顔', 'かお', 'kao', 'muka', 'face'],
                    ['目', 'め', 'me', 'mata', 'eye'],
                    ['耳', 'みみ', 'mimi', 'telinga', 'ear'],
                    ['鼻', 'はな', 'hana', 'hidung', 'nose'],
                    ['口', 'くち', 'kuchi', 'mulut', 'mouth'],
                    ['歯', 'は', 'ha', 'gigi', 'tooth'],
                    ['おなか', 'おなか', 'onaka', 'perut', 'stomach'],
                    ['足', 'あし', 'ashi', 'kaki', 'leg / foot'],
                    ['背', 'せ', 'se', 'punggung', 'back'],
                    ['サービス', 'サービス', 'saabisu', 'pelayanan', 'service'],
                    ['ジョギング', 'ジョギング', 'jogingu', 'joging', 'jogging'],
                    ['シャワー', 'シャワー', 'shawaa', 'shower', 'shower'],
                    ['緑', 'みどり', 'midori', 'hijau, tumbuhan hijau', 'green / greenery'],
                    ['お寺', 'おてら', 'otera', 'wihara', 'Buddhist temple'],
                    ['神社', 'じんじゃ', 'jinja', 'kuil Shinto', 'Shinto shrine'],
                    ['番', 'ばん', '-ban', 'nomor ~ (urutan)', '~ (ordinal number)'],
                    ['どうやって', 'どうやって', 'dou yatte', 'dengan cara bagaimana', 'how, by what means'],
                    ['どの', 'どの', 'dono', '~ yang mana (3 atau lebih)', 'which ~ (three or more)'],
                    ['どれ', 'どれ', 'dore', 'mana (3 atau lebih)', 'which one (three or more)'],
                ],
            ],
            17 => [
                'title_id' => 'Kesehatan & Tubuh',
                'title_en' => 'Health & Body',
                'words' => [
                    ['覚えます', 'おぼえます', 'oboemasu', 'mengingat, menghafal', 'remember'],
                    ['忘れます', 'わすれます', 'wasuremasu', 'lupa', 'forget'],
                    ['なくします', 'なくします', 'nakushimasu', 'kehilangan', 'lose'],
                    ['払います', 'はらいます', 'haraimasu', 'membayar', 'pay'],
                    ['返します', 'かえします', 'kaeshimasu', 'mengembalikan', 'return (something)'],
                    ['出かけます', 'でかけます', 'dekakemasu', 'pergi, keluar, berangkat', 'go out'],
                    ['脱ぎます', 'ぬぎます', 'nugimasu', 'buka (baju, sepatu)', 'take off (clothes)'],
                    ['持って行きます', 'もっていきます', 'motte ikimasu', 'membawa pergi', 'take (something) along'],
                    ['持って来ます', 'もってきます', 'motte kimasu', 'membawa datang', 'bring (something)'],
                    ['心配します', 'しんぱいします', 'shinpaishimasu', 'mengkhawatirkan', 'worry'],
                    ['残業します', 'ざんぎょうします', 'zangyoushimasu', 'melembur', 'work overtime'],
                    ['出張します', 'しゅっちょうします', 'shucchoushimasu', 'dinas', 'go on a business trip'],
                    ['大切', 'たいせつ', 'taisetsu', 'penting, berharga', 'important'],
                    ['大丈夫', 'だいじょうぶ', 'daijoubu', 'tidak apa-apa', 'okay / fine'],
                    ['危ない', 'あぶない', 'abunai', 'berbahaya', 'dangerous'],
                    ['禁煙', 'きんえん', 'kinen', 'dilarang merokok', 'no smoking'],
                    ['保険証', 'ほけんしょう', 'hokenshou', 'kartu asuransi kesehatan', 'insurance card'],
                    ['熱', 'ねつ', 'netsu', 'demam', 'fever'],
                    ['病気', 'びょうき', 'byouki', 'sakit', 'illness'],
                    ['薬', 'くすり', 'kusuri', 'obat', 'medicine'],
                    ['風呂', 'ふろ', 'furo', 'mandi, kamar mandi', 'bath'],
                    ['上着', 'うわぎ', 'uwagi', 'baju, jaket', 'jacket'],
                    ['下着', 'したぎ', 'shitagi', 'pakaian dalam', 'underwear'],
                    ['ですから', 'ですから', 'desukara', 'oleh karena itu', 'therefore, so'],
                ],
            ],
            18 => [
                'title_id' => 'Kemampuan & Hobi',
                'title_en' => 'Abilities & Hobbies',
                'words' => [
                    ['できます', 'できます', 'dekimasu', 'dapat, bisa, mampu', 'can do'],
                    ['洗います', 'あらいます', 'araimasu', 'mencuci', 'wash'],
                    ['弾きます', 'ひきます', 'hikimasu', 'bermain (alat musik)', 'play (instrument)'],
                    ['歌います', 'うたいます', 'utaimasu', 'bernyanyi, menyanyi', 'sing'],
                    ['集めます', 'あつめます', 'atsumemasu', 'mengumpulkan', 'collect'],
                    ['捨てます', 'すてます', 'sutemasu', 'membuang', 'throw away'],
                    ['換えます', 'かえます', 'kaemasu', 'mengganti, menukar', 'exchange'],
                    ['運転します', 'うんてんします', 'untenshimasu', 'menyetir, mengendarai', 'drive'],
                    ['予約します', 'よやくします', 'yoyakushimasu', 'memesan', 'reserve / book'],
                    ['ピアノ', 'ピアノ', 'piano', 'piano', 'piano'],
                    ['メートル', 'メートル', 'meetoru', 'meter', 'meter'],
                    ['現金', 'げんきん', 'genkin', 'uang tunai', 'cash'],
                    ['趣味', 'しゅみ', 'shumi', 'hobi, kegemaran', 'hobby'],
                    ['日記', 'にっき', 'nikki', 'catatan harian', 'diary'],
                    ['お祈り', 'おいのり', 'oinori', 'doa', 'prayer'],
                    ['課長', 'かちょう', 'kachou', 'kepala seksi', 'section chief'],
                    ['部長', 'ぶちょう', 'buchou', 'kepala bagian', 'department head'],
                    ['社長', 'しゃちょう', 'shachou', 'direktur utama', 'company president'],
                    ['動物', 'どうぶつ', 'doubutsu', 'hewan, binatang', 'animal'],
                    ['馬', 'うま', 'uma', 'kuda', 'horse'],
                    ['インターネット', 'インターネット', 'intaanetto', 'internet', 'internet'],
                ],
            ],
            19 => [
                'title_id' => 'Pengalaman & Kebiasaan',
                'title_en' => 'Experience & Habits',
                'words' => [
                    ['登ります', 'のぼります', 'noborimasu', 'naik', 'climb'],
                    ['泊まります', 'とまります', 'tomarimasu', 'menginap', 'stay overnight'],
                    ['掃除します', 'そうじします', 'soujishimasu', 'membersihkan', 'clean'],
                    ['洗濯します', 'せんたくします', 'sentakushimasu', 'mencuci pakaian', 'do laundry'],
                    ['なります', 'なります', 'narimasu', 'menjadi', 'become'],
                    ['眠い', 'ねむい', 'nemui', 'mengantuk', 'sleepy'],
                    ['強い', 'つよい', 'tsuyoi', 'kuat', 'strong'],
                    ['弱い', 'よわい', 'yowai', 'lemah', 'weak'],
                    ['練習', 'れんしゅう', 'renshuu', 'latihan', 'practice'],
                    ['ゴルフ', 'ゴルフ', 'gorufu', 'golf', 'golf'],
                    ['相撲', 'すもう', 'sumou', 'sumo', 'sumo'],
                    ['お茶', 'おちゃ', 'ocha', 'upacara minum teh', 'tea ceremony'],
                    ['日', 'ひ', 'hi', 'hari', 'day'],
                    ['調子', 'ちょうし', 'choushi', 'kondisi', 'condition'],
                    ['一度', 'いちど', 'ichido', 'sekali', 'once'],
                    ['一度も', 'いちども', 'ichidomo', 'sekali-kali (negatif)', 'not even once'],
                    ['だんだん', 'だんだん', 'dandan', 'berangsur-angsur', 'gradually'],
                    ['もうすぐ', 'もうすぐ', 'mou sugu', 'tidak lama lagi', 'soon'],
                    ['おかげさまで', 'おかげさまで', 'okagesamade', 'atas berkat', 'thankfully'],
                    ['でも', 'でも', 'demo', 'tetapi', 'but'],
                ],
            ],
            20 => [
                'title_id' => 'Bentuk Biasa & Sapaan',
                'title_en' => 'Plain Form & Address Terms',
                'words' => [
                    ['要ります', 'いります', 'irimasu', 'memerlukan (visa)', 'need (a visa)'],
                    ['調べます', 'しらべます', 'shirabemasu', 'memeriksa, meneliti', 'check / investigate'],
                    ['修理します', 'しゅうりします', 'shuurishimasu', 'memperbaiki', 'repair'],
                    ['僕', 'ぼく', 'boku', 'aku (laki-laki)', 'I (male, casual)'],
                    ['君', 'きみ', 'kimi', 'kamu', 'you (casual)'],
                    ['君', 'くん', '-kun', 'Sdr. ~ (informal)', '(informal honorific)'],
                    ['うん', 'うん', 'un', 'ya (informal)', 'yeah'],
                    ['ううん', 'ううん', 'uun', 'tidak (informal)', 'nope'],
                    ['ことば', 'ことば', 'kotoba', 'kata, bahasa', 'word / language'],
                    ['着物', 'きもの', 'kimono', 'kimono', 'kimono'],
                    ['ビザ', 'ビザ', 'biza', 'VISA', 'visa'],
                    ['初め', 'はじめ', 'hajime', 'awal, mula-mula', 'beginning'],
                    ['終わり', 'おわり', 'owari', 'akhir', 'end'],
                    ['こっち', 'こっち', 'kocchi', 'sini (informal)', 'here (casual)'],
                    ['そっち', 'そっち', 'socchi', 'situ (informal)', 'there (casual)'],
                    ['あっち', 'あっち', 'acchi', 'sana (informal)', 'over there (casual)'],
                    ['どっち', 'どっち', 'docchi', 'mana (informal)', 'which (casual)'],
                ],
            ],
            21 => [
                'title_id' => 'Pendapat & Jabatan',
                'title_en' => 'Opinions & Positions',
                'words' => [
                    ['思います', 'おもいます', 'omoimasu', 'mengira, berpikir', 'think'],
                    ['言います', 'いいます', 'iimasu', 'mengatakan, berkata', 'say'],
                    ['勝ちます', 'かちます', 'kachimasu', 'menang', 'win'],
                    ['負けます', 'まけます', 'makemasu', 'kalah', 'lose'],
                    ['役に立ちます', 'やくにたちます', 'yaku ni tachimasu', 'berguna, bermanfaat', 'be useful'],
                    ['動きます', 'うごきます', 'ugokimasu', 'pindah, bergerak', 'move'],
                    ['やめます', 'やめます', 'yamemasu', 'berhenti (kerja)', 'quit'],
                    ['気をつけます', 'きをつけます', 'ki o tsukemasu', 'berwaspada, berhati-hati', 'be careful'],
                    ['留学します', 'りゅうがくします', 'ryuugakushimasu', 'studi di luar negeri', 'study abroad'],
                    ['むだ', 'むだ', 'muda', 'sia-sia, tidak berguna', 'wasteful'],
                    ['不便', 'ふべん', 'fuben', 'tidak praktis', 'inconvenient'],
                    ['すごい', 'すごい', 'sugoi', 'hebat, bukan main', 'amazing'],
                    ['ほんとう', 'ほんとう', 'hontou', 'betul, benar', 'true'],
                    ['うそ', 'うそ', 'uso', 'bohong', 'lie'],
                    ['自動車', 'じどうしゃ', 'jidousha', 'mobil', 'automobile'],
                    ['交通', 'こうつう', 'koutsuu', 'lalu lintas', 'traffic'],
                    ['物価', 'ぶっか', 'bukka', 'harga barang', 'prices'],
                    ['放送', 'ほうそう', 'housou', 'siaran, pengumuman', 'broadcast'],
                    ['ニュース', 'ニュース', 'nyuusu', 'warta berita', 'news'],
                    ['アニメ', 'アニメ', 'anime', 'animasi', 'anime'],
                    ['マンガ', 'マンガ', 'manga', 'manga, komik', 'manga / comic'],
                    ['デザイン', 'デザイン', 'dezain', 'desain, model', 'design'],
                    ['夢', 'ゆめ', 'yume', 'mimpi', 'dream'],
                    ['天才', 'てんさい', 'tensai', 'genius', 'genius'],
                    ['試合', 'しあい', 'shiai', 'pertandingan', 'match / game'],
                ],
            ],
            22 => [
                'title_id' => 'Pakaian & Penampilan',
                'title_en' => 'Clothing & Appearance',
                'words' => [
                    ['着ます', 'きます', 'kimasu', 'memakai (kemeja)', 'wear (shirt)'],
                    ['はきます', 'はきます', 'hakimasu', 'memakai (sepatu, celana)', 'wear (shoes/pants)'],
                    ['かぶります', 'かぶります', 'kaburimasu', 'memakai (topi)', 'wear (hat)'],
                    ['かけます', 'かけます', 'kakemasu', 'memakai kaca mata', 'wear (glasses)'],
                    ['生まれます', 'うまれます', 'umaremasu', 'lahir', 'be born'],
                    ['わたしたち', 'わたしたち', 'watashitachi', 'kami, kita', 'we'],
                    ['コート', 'コート', 'kooto', 'mantel', 'coat'],
                    ['セーター', 'セーター', 'seetaa', 'sweater', 'sweater'],
                    ['スーツ', 'スーツ', 'suutsu', 'pakaian setelan', 'suit'],
                    ['帽子', 'ぼうし', 'boushi', 'topi', 'hat'],
                    ['眼鏡', 'めがね', 'megane', 'kaca mata', 'glasses'],
                    ['ケーキ', 'ケーキ', 'keeki', 'kue', 'cake'],
                    ['弁当', 'べんとう', 'bentou', 'bekal', 'boxed lunch'],
                    ['ロボット', 'ロボット', 'robotto', 'robot', 'robot'],
                    ['ユーモア', 'ユーモア', 'yuumoa', 'humor', 'humor'],
                    ['都合', 'つごう', 'tsugou', 'kondisi (jadwal)', 'convenience / schedule'],
                    ['よく', 'よく', 'yoku', 'sering kali', 'often'],
                ],
            ],
            23 => [
                'title_id' => 'Jalan & Petunjuk Arah',
                'title_en' => 'Roads & Directions',
                'words' => [
                    ['聞きます', 'ききます', 'kikimasu', 'bertanya (kepada guru)', 'ask (a teacher)'],
                    ['回します', 'まわします', 'mawashimasu', 'memutar', 'turn / rotate'],
                    ['引きます', 'ひきます', 'hikimasu', 'tarik', 'pull'],
                    ['変えます', 'かえます', 'kaemasu', 'mengubah', 'change'],
                    ['触ります', 'さわります', 'sawarimasu', 'menyentuh (pintu)', 'touch (a door)'],
                    ['出ます', 'でます', 'demasu', 'keluar (uang kembalian)', 'come out (change)'],
                    ['歩きます', 'あるきます', 'arukimasu', 'berjalan kaki', 'walk'],
                    ['渡ります', 'わたります', 'watarimasu', 'menyeberang (jembatan)', 'cross (a bridge)'],
                    ['曲がります', 'まがります', 'magarimasu', 'belok (ke kanan)', 'turn (right)'],
                    ['寂しい', 'さびしい', 'sabishii', 'sepi', 'lonely'],
                    ['お湯', 'おゆ', 'oyu', 'air panas', 'hot water'],
                    ['音', 'おと', 'oto', 'bunyi, suara', 'sound'],
                    ['サイズ', 'サイズ', 'saizu', 'ukuran', 'size'],
                    ['故障', 'こしょう', 'koshou', 'kerusakan', 'breakdown'],
                    ['道', 'みち', 'michi', 'jalan', 'road'],
                    ['交差点', 'こうさてん', 'kousaten', 'perempatan', 'intersection'],
                    ['信号', 'しんごう', 'shingou', 'lampu lalu lintas', 'traffic light'],
                    ['角', 'かど', 'kado', 'sudut', 'corner'],
                    ['橋', 'はし', 'hashi', 'jembatan', 'bridge'],
                    ['駐車場', 'ちゅうしゃじょう', 'chuushajou', 'tempat parkir', 'parking lot'],
                    ['建物', 'たてもの', 'tatemono', 'gedung', 'building'],
                    ['何回も', 'なんかいも', 'nankaimo', 'berkali-kali', 'many times'],
                    ['目', 'め', '-me', 'yang ke- (urutan)', '-th (ordinal)'],
                ],
            ],
            24 => [
                'title_id' => 'Bantuan & Keluarga Besar',
                'title_en' => 'Help & Extended Family',
                'words' => [
                    ['くれます', 'くれます', 'kuremasu', 'diberikan (kepada saya)', 'give (to me)'],
                    ['直します', 'なおします', 'naoshimasu', 'mengoreksi, memperbaiki', 'correct / fix'],
                    ['連れて行きます', 'つれていきます', 'tsurete ikimasu', 'membawa, mengajak pergi', 'take (someone) along'],
                    ['連れて来ます', 'つれてきます', 'tsurete kimasu', 'membawa, mengajak datang', 'bring (someone) along'],
                    ['送ります', 'おくります', 'okurimasu', 'mengantar orang', 'see (someone) off'],
                    ['紹介します', 'しょうかいします', 'shoukaishimasu', 'memperkenalkan', 'introduce'],
                    ['案内します', 'あんないします', 'annaishimasu', 'mengantarkan, memandu', 'guide'],
                    ['説明します', 'せつめいします', 'setsumeishimasu', 'menjelaskan, menerangkan', 'explain'],
                    ['おじいさん', 'おじいさん', 'ojiisan', 'kakek', 'grandfather'],
                    ['おばあさん', 'おばあさん', 'obaasan', 'nenek', 'grandmother'],
                    ['準備', 'じゅんび', 'junbi', 'persiapan', 'preparation'],
                    ['引っ越し', 'ひっこし', 'hikkoshi', 'pindah rumah', 'moving house'],
                    ['お菓子', 'おかし', 'okashi', 'kue, jajanan', 'sweets / snacks'],
                    ['ホームステイ', 'ホームステイ', 'hoomusutei', 'homestay', 'homestay'],
                    ['全部', 'ぜんぶ', 'zenbu', 'semua', 'all'],
                    ['自分で', 'じぶんで', 'jibunde', 'dengan sendiri', 'by oneself'],
                ],
            ],
            25 => [
                'title_id' => 'Pengandaian & Kehidupan',
                'title_en' => 'Conditionals & Life',
                'words' => [
                    ['考えます', 'かんがえます', 'kangaemasu', 'berpikir, memikirkan', 'think over'],
                    ['着きます', 'つきます', 'tsukimasu', 'tiba, sampai', 'arrive'],
                    ['取ります', 'とります', 'torimasu', 'berumur, lanjut usia', 'grow old'],
                    ['足ります', 'たります', 'tarimasu', 'cukup', 'be enough'],
                    ['田舎', 'いなか', 'inaka', 'desa, kampung halaman', 'countryside'],
                    ['チャンス', 'チャンス', 'chansu', 'kesempatan', 'chance'],
                    ['億', 'おく', 'oku', 'ratus juta', 'hundred million'],
                    ['もし', 'もし', 'moshi', 'kalau', 'if'],
                    ['意味', 'いみ', 'imi', 'arti, makna', 'meaning'],
                ],
            ],
        ];
    }
}