<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GrammarSeeder extends Seeder
{
    /**
     * Grammar patterns follow Minna no Nihongo I's standard N5 sequence
     * (a pattern like "Kata Benda1 wa Kata Benda2 desu" is a grammatical
     * fact, not copyrightable). The explanations and example sentences
     * below are written fresh for this app — NOT copied or lightly
     * paraphrased from the book's own explanations/examples.
     */
    public function run(): void
    {
        $grammars = [
            [
                'title_id' => 'KB1 wa KB2 desu',
                'title_en' => 'KB1 wa KB2 desu (X is Y)',
                'pattern' => '〜は〜です',
                'explanation_id' => 'Pola ini dipakai untuk menyatakan bahwa suatu benda atau orang (KB1) adalah sesuatu (KB2). "wa" menandai topik kalimat, dan "desu" mengakhiri kalimat secara sopan.',
                'explanation_en' => 'Use this pattern to state that a person or thing (Noun 1) is a certain thing (Noun 2). "wa" marks the topic, and "desu" politely closes the sentence.',
                'example_japanese' => 'これは かばんです。',
                'example_reading' => 'これは かばんです。',
                'example_translation_id' => 'Ini adalah tas.',
                'example_translation_en' => 'This is a bag.',
                'jlpt_level' => 'N5',
                'order' => 1,
            ],
            [
                'title_id' => 'KB1 wa KB2 ja arimasen',
                'title_en' => 'KB1 wa KB2 ja arimasen (X is not Y)',
                'pattern' => '〜は〜じゃありません',
                'explanation_id' => 'Bentuk negatif dari "desu". Dipakai untuk menyangkal bahwa KB1 adalah KB2. Dalam percakapan santai sering diucapkan "ja nai desu".',
                'explanation_en' => 'The negative form of "desu", used to deny that Noun 1 is Noun 2. In casual speech it is often shortened to "ja nai desu".',
                'example_japanese' => 'あれは とけいじゃありません。',
                'example_reading' => 'あれは とけいじゃありません。',
                'example_translation_id' => 'Itu bukan jam.',
                'example_translation_en' => 'That is not a clock.',
                'jlpt_level' => 'N5',
                'order' => 2,
            ],
            [
                'title_id' => 'Kore/Sore/Are vs Kono/Sono/Ano',
                'title_en' => 'Kore/Sore/Are vs Kono/Sono/Ano',
                'pattern' => 'これ・それ・あれ ／ この・その・あの',
                'explanation_id' => 'これ/それ/あれ berdiri sendiri sebagai kata benda penunjuk ("ini/itu"). この/その/あの harus selalu diikuti kata benda lain untuk menerangkan benda tersebut, tidak bisa berdiri sendiri.',
                'explanation_en' => 'kore/sore/are stand alone as pronouns ("this/that"). kono/sono/ano must always be followed by a noun they describe — they cannot stand alone.',
                'example_japanese' => 'この ほんは わたしのです。それは あなたのです。',
                'example_reading' => 'この ほんは わたしのです。それは あなたのです。',
                'example_translation_id' => 'Buku ini milik saya. Itu milik Anda.',
                'example_translation_en' => 'This book is mine. That one is yours.',
                'jlpt_level' => 'N5',
                'order' => 3,
            ],
            [
                'title_id' => 'KB1 wa KB2 desu ka',
                'title_en' => 'KB1 wa KB2 desu ka (Is X Y?)',
                'pattern' => '〜は〜ですか',
                'explanation_id' => 'Menambahkan partikel akhir "ka" pada kalimat "desu" mengubahnya menjadi pertanyaan, tanpa perlu membalik susunan kata seperti dalam bahasa Indonesia/Inggris. Nada bicara naik sedikit di akhir kalimat.',
                'explanation_en' => 'Adding the sentence-final particle "ka" turns a "desu" statement into a question — the word order never changes, unlike in Indonesian or English. Intonation rises slightly at the end.',
                'example_japanese' => 'すずきさんは かいしゃいんですか。',
                'example_reading' => 'すずきさんは かいしゃいんですか。',
                'example_translation_id' => 'Apakah Suzuki seorang karyawan perusahaan?',
                'example_translation_en' => 'Is Mr./Ms. Suzuki a company employee?',
                'jlpt_level' => 'N5',
                'order' => 4,
            ],
            [
                'title_id' => 'KB1 mo KB2 desu',
                'title_en' => 'KB1 mo KB2 desu (X is also Y)',
                'pattern' => '〜も〜です',
                'explanation_id' => 'Partikel "mo" ("juga") menggantikan posisi "wa" ketika informasi tentang topik yang baru sama dengan topik yang disebut sebelumnya. Tidak pernah dipakai bersamaan dengan "wa" pada kata benda yang sama.',
                'explanation_en' => 'The particle "mo" ("also/too") replaces "wa" whenever the new topic shares the same information just stated about a previous topic. It never appears together with "wa" on the same noun.',
                'example_japanese' => 'ミラーさんは かいしゃいんです。サントスさんも かいしゃいんです。',
                'example_reading' => 'ミラーさんは かいしゃいんです。サントスさんも かいしゃいんです。',
                'example_translation_id' => 'Mr. Miller adalah karyawan perusahaan. Mr. Santos juga karyawan perusahaan.',
                'example_translation_en' => 'Mr. Miller is a company employee. Mr. Santos is also a company employee.',
                'jlpt_level' => 'N5',
                'order' => 5,
            ],
            [
                'title_id' => 'KB1 no KB2',
                'title_en' => 'KB1 no KB2 (KB2 of/belonging to KB1)',
                'pattern' => '〜の〜',
                'explanation_id' => 'Partikel "no" menghubungkan dua kata benda, di mana KB1 menerangkan atau memiliki KB2 — mirip fungsi "of/\'s" dalam bahasa Inggris, tapi urutannya terbalik: pemilik/keterangan disebut lebih dulu. Bisa untuk kepemilikan (saya punya), asal (negara/perusahaan), atau jenis (buku bahasa Jepang).',
                'explanation_en' => 'The particle "no" links two nouns, where the first noun describes or owns the second — similar to English "of/\'s", but the order is reversed: the owner/descriptor comes first. It covers possession, origin (company/country), or category (a Japanese-language book).',
                'example_japanese' => 'これは わたしの ほんです。',
                'example_reading' => 'これは わたしの ほんです。',
                'example_translation_id' => 'Ini adalah buku saya.',
                'example_translation_en' => 'This is my book.',
                'jlpt_level' => 'N5',
                'order' => 6,
            ],
            [
                'title_id' => 'KB (pengganti KB yang sudah jelas)',
                'title_en' => 'no as a pronoun (dropping a known noun)',
                'pattern' => '〜の (代名詞)',
                'explanation_id' => 'Ketika kata benda kedua sudah jelas dari konteks percakapan, "no" bisa berdiri sendiri menggantikan kata benda tersebut, sehingga tidak perlu diulang. Contoh: daripada mengulang "kaban" (tas), cukup katakan "no" saja.',
                'explanation_en' => 'When the second noun is already clear from context, "no" can stand alone in its place so the noun does not need to be repeated. For instance, instead of repeating "kaban" (bag), the speaker simply says "no".',
                'example_japanese' => 'Aさんの かばんですか。－いいえ、わたしのじゃありません。',
                'example_reading' => 'Aさんの かばんですか。－いいえ、わたしのじゃありません。',
                'example_translation_id' => 'Apakah ini tas milik A? — Bukan, ini bukan punya saya.',
                'example_translation_en' => 'Is this A\'s bag? — No, it isn\'t mine.',
                'jlpt_level' => 'N5',
                'order' => 7,
            ],
            [
                'title_id' => 'Soko/Asoko/Koko (kata tunjuk tempat)',
                'title_en' => 'Koko/Soko/Asoko (place pointing words)',
                'pattern' => 'ここ・そこ・あそこ',
                'explanation_id' => 'Kelompok kata tunjuk untuk tempat, sejalan dengan kore/sore/are untuk benda. "koko" = di sini (dekat pembicara), "soko" = di situ (dekat lawan bicara), "asoko" = di sana (jauh dari keduanya). "doko" adalah bentuk tanyanya ("di mana").',
                'explanation_en' => 'These are the place-pointing counterparts to kore/sore/are. "koko" = here (near the speaker), "soko" = there (near the listener), "asoko" = over there (far from both). "doko" is the question form, "where".',
                'example_japanese' => 'すみません、といれは どこですか。－あそこです。',
                'example_reading' => 'すみません、といれは どこですか。－あそこです。',
                'example_translation_id' => 'Permisi, toiletnya di mana? — Di sana.',
                'example_translation_en' => 'Excuse me, where is the restroom? — Over there.',
                'jlpt_level' => 'N5',
                'order' => 8,
            ],
            [
                'title_id' => 'Sou desu / Sou ja arimasen',
                'title_en' => 'Sou desu / Sou ja arimasen (confirming or denying)',
                'pattern' => 'そうです・そうじゃありません',
                'explanation_id' => 'Dipakai untuk membenarkan ("ya, betul") atau menyangkal ("bukan") pertanyaan berjenis ya/tidak yang memakai "desu ka". "Sou" menggantikan seluruh isi kalimat sebelumnya supaya tidak perlu diulang.',
                'explanation_en' => 'Used to confirm ("yes, that\'s right") or deny ("no, it isn\'t") a yes/no question ending in "desu ka". "Sou" stands in for the whole previous statement so it doesn\'t need repeating.',
                'example_japanese' => 'ミラーさんは アメリカ人ですか。－はい、そうです。',
                'example_reading' => 'ミラーさんは アメリカ人ですか。－はい、そうです。',
                'example_translation_id' => 'Apakah Mr. Miller orang Amerika? — Ya, betul.',
                'example_translation_en' => 'Is Mr. Miller American? — Yes, that\'s right.',
                'jlpt_level' => 'N5',
                'order' => 9,
            ],
            [
                'title_id' => 'KB1 ka, KB2 ka',
                'title_en' => 'KB1 ka, KB2 ka (Is it A or B?)',
                'pattern' => '〜か、〜か',
                'explanation_id' => 'Untuk bertanya memilih di antara dua pilihan, dua kalimat "desu ka" digabung dengan mengulang partikel "ka" setelah pilihan pertama. Jawabannya menyebut salah satu pilihan, bukan "ya/tidak".',
                'explanation_en' => 'To ask the listener to choose between two options, two "desu ka" clauses are joined by repeating "ka" after the first option. The answer names one of the choices rather than "yes/no".',
                'example_japanese' => 'これは ボールペンですか、シャープペンシルですか。－シャープペンシルです。',
                'example_reading' => 'これは ボールペンですか、シャープペンシルですか。－シャープペンシルです。',
                'example_translation_id' => 'Ini pulpen atau pensil mekanik? — Pensil mekanik.',
                'example_translation_en' => 'Is this a ballpoint pen or a mechanical pencil? — A mechanical pencil.',
                'jlpt_level' => 'N5',
                'order' => 10,
            ],
            [
                'title_id' => 'Nan no KB',
                'title_en' => 'Nan no KB (a KB for/about what?)',
                'pattern' => '何の〜',
                'explanation_id' => '"Nan no" dipakai sebelum kata benda untuk menanyakan kegunaan, isi, atau jenis dari benda itu — bukan bendanya apa, tapi "tentang/untuk apa" benda itu.',
                'explanation_en' => '"Nan no" comes before a noun to ask about that thing\'s purpose, content, or category — not what the object itself is, but what it is for or about.',
                'example_japanese' => 'それは 何の 雑誌ですか。－日本語の 雑誌です。',
                'example_reading' => 'それは 何の 雑誌ですか。－日本語の 雑誌です。',
                'example_translation_id' => 'Itu majalah tentang apa? — Majalah bahasa Jepang.',
                'example_translation_en' => 'What is that magazine about? — It\'s a Japanese-language magazine.',
                'jlpt_level' => 'N5',
                'order' => 11,
            ],
            [
                'title_id' => 'Kochira/Sochira/Achira/Dochira',
                'title_en' => 'Kochira/Sochira/Achira/Dochira (polite direction words)',
                'pattern' => 'こちら・そちら・あちら・どちら',
                'explanation_id' => 'Versi lebih sopan dari koko/soko/asoko/doko, dipakai untuk menunjuk arah atau tempat secara halus — misalnya saat mengarahkan tamu — dan juga bisa dipakai untuk memperkenalkan orang secara sopan.',
                'explanation_en' => 'A more polite version of koko/soko/asoko/doko, used to point to a direction or place gently — such as when guiding a guest — and can also be used to politely introduce a person.',
                'example_japanese' => 'エレベーターは あちらです。',
                'example_reading' => 'エレベーターは あちらです。',
                'example_translation_id' => 'Liftnya di sebelah sana.',
                'example_translation_en' => 'The elevator is that way.',
                'jlpt_level' => 'N5',
                'order' => 12,
            ],
            [
                'title_id' => 'KB (tempat) wa KB2 desu',
                'title_en' => 'Place wa Thing desu (locating something)',
                'pattern' => '(場所)は〜です',
                'explanation_id' => 'Pola "wa...desu" yang sama seperti Pelajaran 1 dipakai juga untuk menyatakan letak suatu benda/ruangan, dengan menjadikan nama tempat sebagai topik dan menyebutkan apa yang ada di sana.',
                'explanation_en' => 'The same "wa...desu" pattern from Lesson 1 is reused to state where something is, by making the place the topic and naming what belongs there.',
                'example_japanese' => '事務所は 2かいです。',
                'example_reading' => '事務所は 2かいです。',
                'example_translation_id' => 'Kantornya ada di lantai 2.',
                'example_translation_en' => 'The office is on the 2nd floor.',
                'jlpt_level' => 'N5',
                'order' => 13,
            ],
            [
                'title_id' => 'Ima KB1 ji KB2 fun desu',
                'title_en' => 'Ima ~ji ~fun desu (telling the current time)',
                'pattern' => '今 〜時〜分です',
                'explanation_id' => 'Cara paling dasar menyebutkan pukul berapa sekarang: "ima" (sekarang) + angka jam + "ji" + angka menit + "fun/pun" + "desu". Beberapa angka menit berubah bunyi (misalnya 3-pun, 4-pun jadi yon-pun).',
                'explanation_en' => 'The basic way to say the current time: "ima" (now) + hour number + "ji" + minute number + "fun/pun" + "desu". A few minute counters shift sound (e.g. 3 minutes = san-pun, 4 minutes = yon-pun).',
                'example_japanese' => '今 4時半です。',
                'example_reading' => '今 4時半です。',
                'example_translation_id' => 'Sekarang jam setengah 5 (4:30).',
                'example_translation_en' => 'It is now 4:30.',
                'jlpt_level' => 'N5',
                'order' => 14,
            ],
            [
                'title_id' => 'KB1 kara KB2 made',
                'title_en' => 'KB1 kara KB2 made (from X until Y)',
                'pattern' => '〜から〜まで',
                'explanation_id' => '"Kara" menandai titik awal dan "made" menandai titik akhir suatu rentang, baik rentang waktu maupun tempat. Keduanya bisa dipakai bersama atau sendiri-sendiri.',
                'explanation_en' => '"Kara" marks the starting point and "made" marks the ending point of a range — whether of time or of place. They can be used together or on their own.',
                'example_japanese' => '銀行は 9時から 3時までです。',
                'example_reading' => '銀行は 9時から 3時までです。',
                'example_translation_id' => 'Bank buka dari jam 9 sampai jam 3.',
                'example_translation_en' => 'The bank is open from 9 to 3.',
                'jlpt_level' => 'N5',
                'order' => 15,
            ],
            [
                'title_id' => 'Mainichi/Maiasa/Maiban + Kata Kerja',
                'title_en' => 'Mainichi/Maiasa/Maiban + verb (daily routines)',
                'pattern' => '毎日・毎朝・毎晩〜',
                'explanation_id' => 'Kata keterangan frekuensi seperti "mainichi" (setiap hari), "maiasa" (setiap pagi), dan "maiban" (setiap malam) diletakkan sebelum kata kerja untuk menyatakan rutinitas yang berulang.',
                'explanation_en' => 'Frequency adverbs like "mainichi" (every day), "maiasa" (every morning), and "maiban" (every night) are placed before the verb to describe a repeated routine.',
                'example_japanese' => '毎朝、6時に 起きます。',
                'example_reading' => '毎朝、6時に 起きます。',
                'example_translation_id' => 'Setiap pagi saya bangun jam 6.',
                'example_translation_en' => 'I wake up at 6 every morning.',
                'jlpt_level' => 'N5',
                'order' => 16,
            ],
            [
                'title_id' => 'KB(tempat) e ikimasu/kimasu/kaerimasu',
                'title_en' => 'Place e ikimasu/kimasu/kaerimasu (go/come/return to)',
                'pattern' => '〜へ 行きます・来ます・帰ります',
                'explanation_id' => 'Partikel "e" (ditulis へ tapi dibaca "e") menandai arah tujuan gerakan setelah kata kerja "ikimasu" (pergi), "kimasu" (datang), atau "kaerimasu" (pulang). Partikel "ni" bisa dipakai bergantian dengan makna yang sama.',
                'explanation_en' => 'The particle "e" (written へ but pronounced "e") marks the direction of movement before the verbs "ikimasu" (go), "kimasu" (come), or "kaerimasu" (return). "Ni" can be used interchangeably here with the same meaning.',
                'example_japanese' => '来週 国へ 帰ります。',
                'example_reading' => '来週 国へ 帰ります。',
                'example_translation_id' => 'Minggu depan saya pulang ke negara asal.',
                'example_translation_en' => 'Next week I\'m going back to my home country.',
                'jlpt_level' => 'N5',
                'order' => 17,
            ],
            [
                'title_id' => 'Kendaraan de ikimasu',
                'title_en' => 'Vehicle de ikimasu (going by means of)',
                'pattern' => '〜で 行きます',
                'explanation_id' => 'Partikel "de" setelah nama alat transportasi menandai cara/sarana melakukan suatu gerakan. Untuk berjalan kaki, dipakai frasa khusus "aruite" tanpa partikel "de".',
                'explanation_en' => 'The particle "de" after a vehicle name marks the means used to move. For going on foot, the special phrase "aruite" is used instead, without the particle "de".',
                'example_japanese' => 'バスで 会社へ 行きます。',
                'example_reading' => 'バスで 会社へ 行きます。',
                'example_translation_id' => 'Saya pergi ke kantor naik bus.',
                'example_translation_en' => 'I go to the office by bus.',
                'jlpt_level' => 'N5',
                'order' => 18,
            ],
            [
                'title_id' => 'Orang to issho ni',
                'title_en' => 'Person to issho ni (together with someone)',
                'pattern' => '〜と 一緒に',
                'explanation_id' => 'Partikel "to" setelah nama/kata ganti orang menandai orang yang menemani, diikuti "issho ni" (bersama-sama) sebelum kata kerja. Kalau sendirian, dipakai "hitori de" sebagai gantinya.',
                'explanation_en' => 'The particle "to" after a person\'s name/pronoun marks the companion, followed by "issho ni" (together) before the verb. When alone, "hitori de" is used instead.',
                'example_japanese' => '家族と 一緒に 旅行します。',
                'example_reading' => '家族と 一緒に 旅行します。',
                'example_translation_id' => 'Saya bepergian bersama keluarga.',
                'example_translation_en' => 'I travel together with my family.',
                'jlpt_level' => 'N5',
                'order' => 19,
            ],
        ];

        foreach ($grammars as $grammar) {
            \App\Models\Grammar::firstOrCreate(
                ['pattern' => $grammar['pattern']],
                $grammar
            );
        }
    }
}
