name: build-release
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci --legacy-peer-deps
      - run: npm run build
      - name: Push ke branch release
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout --orphan release-tmp
          git add -A
          git add -f public/build
          git commit -m "release ${GITHUB_SHA::7}"
          git push -f origin HEAD:release
